/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import view.tourview;
/**
 *
 * @author LINH
 */
public class mainview extends javax.swing.JFrame {
    String maNV, tenNV;
    /**
     * Creates new form test
     */
    
    public mainview() {
        initComponents();
    }

    public mainview(String maNV, String tenNV) {
        this.maNV = maNV;
        this.tenNV = tenNV;
        initComponents(); 
        txtMa.setText(maNV);
        txtTen.setText(tenNV);
    }

    public String getMaNV() {
        return maNV;
    }

    public String getTenNV() {
        return tenNV;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        btnTour = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnService = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSale = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCustom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInvoice = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEmployee = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuide = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTen = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        sidepanel.setBackground(new java.awt.Color(0, 51, 102));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTour.setBackground(new java.awt.Color(33, 81, 129));
        btnTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTourMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tour-30.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tour");

        javax.swing.GroupLayout btnTourLayout = new javax.swing.GroupLayout(btnTour);
        btnTour.setLayout(btnTourLayout);
        btnTourLayout.setHorizontalGroup(
            btnTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTourLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnTourLayout.setVerticalGroup(
            btnTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btnTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 50));

        btnService.setBackground(new java.awt.Color(33, 81, 129));
        btnService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnServiceMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-bike-30.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dịch vụ");

        javax.swing.GroupLayout btnServiceLayout = new javax.swing.GroupLayout(btnService);
        btnService.setLayout(btnServiceLayout);
        btnServiceLayout.setHorizontalGroup(
            btnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnServiceLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        btnServiceLayout.setVerticalGroup(
            btnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btnService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 50));

        btnSale.setBackground(new java.awt.Color(33, 81, 129));
        btnSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaleMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sale-30.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Khuyến mãi");

        javax.swing.GroupLayout btnSaleLayout = new javax.swing.GroupLayout(btnSale);
        btnSale.setLayout(btnSaleLayout);
        btnSaleLayout.setHorizontalGroup(
            btnSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSaleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        btnSaleLayout.setVerticalGroup(
            btnSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel.add(btnSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 50));

        btnCustom.setBackground(new java.awt.Color(33, 81, 129));
        btnCustom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCustomMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-customer-30.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Khách hàng");

        javax.swing.GroupLayout btnCustomLayout = new javax.swing.GroupLayout(btnCustom);
        btnCustom.setLayout(btnCustomLayout);
        btnCustomLayout.setHorizontalGroup(
            btnCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCustomLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        btnCustomLayout.setVerticalGroup(
            btnCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCustomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel.add(btnCustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 50));

        btnInvoice.setBackground(new java.awt.Color(33, 81, 129));
        btnInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInvoiceMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-bill-30.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hóa đơn");

        javax.swing.GroupLayout btnInvoiceLayout = new javax.swing.GroupLayout(btnInvoice);
        btnInvoice.setLayout(btnInvoiceLayout);
        btnInvoiceLayout.setHorizontalGroup(
            btnInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInvoiceLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        btnInvoiceLayout.setVerticalGroup(
            btnInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btnInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 50));

        btnEmployee.setBackground(new java.awt.Color(33, 81, 129));
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmployeeMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-employee-30.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nhân viên");

        javax.swing.GroupLayout btnEmployeeLayout = new javax.swing.GroupLayout(btnEmployee);
        btnEmployee.setLayout(btnEmployeeLayout);
        btnEmployeeLayout.setHorizontalGroup(
            btnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEmployeeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        btnEmployeeLayout.setVerticalGroup(
            btnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 220, 50));

        btnGuide.setBackground(new java.awt.Color(33, 81, 129));
        btnGuide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuideMousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-guide-30.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Guide");

        javax.swing.GroupLayout btnGuideLayout = new javax.swing.GroupLayout(btnGuide);
        btnGuide.setLayout(btnGuideLayout);
        btnGuideLayout.setHorizontalGroup(
            btnGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuideLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        btnGuideLayout.setVerticalGroup(
            btnGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel.add(btnGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 220, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TourWizard");
        sidepanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 50));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, 10));
        sidepanel.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 700, 100, -1));
        sidepanel.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 100, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Họ tên");
        sidepanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mã NV");
        sidepanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        sidepanel.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, -1, -1));

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTourMousePressed
        try {
            showFrame(new tourview());
        } catch (SQLException ex) {
            Logger.getLogger(mainview.class.getName()).log(Level.SEVERE, null, ex);
        }
        setColor(btnTour);
        resetColor(btnCustom);
        resetColor(btnEmployee);
        resetColor(btnInvoice);
        resetColor(btnSale);
        resetColor(btnService);
        resetColor(btnGuide);
    }//GEN-LAST:event_btnTourMousePressed

    private void btnServiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiceMousePressed
        // TODO add your handling code here:
        showFrame(new dichvuview());
        setColor(btnService);
        resetColor(btnCustom);
        resetColor(btnEmployee);
        resetColor(btnInvoice);
        resetColor(btnSale);
        resetColor(btnTour);
        resetColor(btnGuide);
    }//GEN-LAST:event_btnServiceMousePressed

    private void btnSaleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaleMousePressed
        // TODO add your handling code here:
        showFrame(new khuyenmaiview());
        setColor(btnSale);
        resetColor(btnCustom);
        resetColor(btnEmployee);
        resetColor(btnInvoice);
        resetColor(btnTour);
        resetColor(btnService);
        resetColor(btnGuide);
    }//GEN-LAST:event_btnSaleMousePressed

    private void btnCustomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomMousePressed
        // TODO add your handling code here:
        showFrame(new khachhangview());
        setColor(btnCustom);
        resetColor(btnTour);
        resetColor(btnEmployee);
        resetColor(btnInvoice);
        resetColor(btnSale);
        resetColor(btnService);
        resetColor(btnGuide);
    }//GEN-LAST:event_btnCustomMousePressed

    private void btnInvoiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMousePressed
        try {
            // TODO add your handling code here:
            showFrame(new hoadonview());
        } catch (SQLException ex) {
            Logger.getLogger(mainview.class.getName()).log(Level.SEVERE, null, ex);
        }
        setColor(btnInvoice);
        resetColor(btnTour);
        resetColor(btnEmployee);
        resetColor(btnCustom);
        resetColor(btnSale);
        resetColor(btnService);
        resetColor(btnGuide);
    }//GEN-LAST:event_btnInvoiceMousePressed

    private void btnEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMousePressed
        // TODO add your handling code here:
        showFrame(new nhanvienview());
        setColor(btnEmployee);
        resetColor(btnCustom);
        resetColor(btnTour);
        resetColor(btnInvoice);
        resetColor(btnSale);
        resetColor(btnService);
        resetColor(btnGuide);
    }//GEN-LAST:event_btnEmployeeMousePressed

    private void btnGuideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuideMousePressed
        // TODO add your handling code here:
        showFrame(new guideview());
        setColor(btnGuide);
        resetColor(btnEmployee);
        resetColor(btnCustom);
        resetColor(btnTour);
        resetColor(btnInvoice);
        resetColor(btnSale);
        resetColor(btnService);
    }//GEN-LAST:event_btnGuideMousePressed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        new dangnhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed
    void setColor(JPanel panel){
        panel.setBackground(new Color(29,90,151));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(33,81,129));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCustom;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JPanel btnEmployee;
    private javax.swing.JPanel btnGuide;
    private javax.swing.JPanel btnInvoice;
    private javax.swing.JPanel btnSale;
    private javax.swing.JPanel btnService;
    private javax.swing.JPanel btnTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

  public void showFrame(JFrame frame) {
        mainpanel.removeAll();
        mainpanel.add(frame.getContentPane());
        mainpanel.revalidate();
        mainpanel.repaint();
    }
}
  
