/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.tour;
import service.tourservice;
import view.dichvuview;
import util.connectdb;
import java.sql.Connection;
import javax.swing.JOptionPane;
import model.KhachHang;
import service.KhachHangService;
import java.time.LocalDate;
import java.util.Date;
/**
 *
 * @author LINH
 */
public class tourview extends javax.swing.JFrame {
    KhachHangService khs = new KhachHangService();
    ArrayList<KhachHang> listKH = new ArrayList<>();
    private ArrayList<tour> lst;
    private tourservice toursc;
    private Connection conn;

    /**
     * Creates new form test
     */
    public tourview() throws SQLException {
        initComponents();
        toursc =new tourservice();
        this.getDataTour();
        this.displayToTable();
        this.displayToControl(index);
        vh();
        fen();
    }
    public void vh(){
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        lblHinhTour.setEnabled(false);
    }
    public void getDataTour() throws SQLException{
        lst=toursc.getData();
    }
    public void displayToTable(){
        DefaultTableModel model = (DefaultTableModel) tblTour.getModel();
        model.setNumRows(0);
        for(tour tr : lst){
            Object[] row = {tr.getMaTour(), tr.getTenTour(), tr.getMaDiaDiem(), tr.getHinhAnhTour(), tr.getThoiGian(), tr.getGiaNguoiLon(), tr.getGiaTreEm(), tr.getNgayBatDau(), tr.getNgayKetThuc(), tr.getMoTaTour()};
            model.addRow(row);
        }
    }
    
    int index=0;
    public void displayToControl(int index){
        tour tr=lst.get(index);
        txtMaTour.setText(tr.getMaTour());
        txtTenTour.setText(tr.getTenTour());
        txtMaDD.setText(tr.getMaDiaDiem());
        txtThoiGian.setText(tr.getThoiGian());
        txtGiaNL.setText(String.valueOf(tr.getGiaNguoiLon()));
        txtGiaTE.setText(String.valueOf(tr.getGiaTreEm()));
        dcNgayBD.setDate(tr.getNgayBatDau());
        jDateChooser2.setDate(tr.getNgayBatDau());
        txtMoTa.setText(tr.getMoTaTour());
        uphinh(tr.getHinhAnhTour());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNgayBatDau = new javax.swing.JTextField();
        txtNgayKetThuc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblHinhTour = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTour = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtTimMa = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTenTour = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        txtMaTour = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtMaDD = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtGiaNL = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtGiaTE = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        dcNgayBD = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTaomoi = new javax.swing.JButton();

        jLabel17.setText("jLabel17");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tour");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lblHinhTour.setText("Thêm hình ảnh");
        lblHinhTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhTourMouseClicked(evt);
            }
        });

        tblTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã tour", "Tên tour", "Mã địa điểm", "Hình ảnh", "Thời gian", "Giá người lớn", "Giá trẻ em", "Ngày bắt đầu", "Ngày kết thúc", "Mô tả"
            }
        ));
        tblTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTour);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimMa, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnTimkiem)
                .addGap(9, 9, 9))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel26.setText("Tên tour:");

        txtTenTour.setColumns(20);
        txtTenTour.setRows(5);
        jScrollPane3.setViewportView(txtTenTour);

        jLabel19.setText("Mã tour:");

        jLabel22.setText("Mã địa điểm:");

        jLabel20.setText("Thời gian:");

        jLabel23.setText("Giá người lớn:");

        jLabel27.setText("Giá trẻ em:");

        jLabel21.setText("Ngày bắt đầu:");

        jLabel24.setText("Ngày kết thúc:");

        jLabel18.setText("Mô tả:");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGiaNL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaDD, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(32, 32, 32)
                                .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGiaTE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(dcNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel18)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dcNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTaomoi.setText("Tạo mới");
        btnTaomoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaomoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSua)
                            .addComponent(btnThem))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa)
                            .addComponent(btnTaomoi)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnRefresh)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaomoi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblHinhTour, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHinhTour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTourMouseClicked
        // TODO add your handling code here:
        int index=tblTour.getSelectedRow();
        this.displayToControl(index);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        lblHinhTour.setEnabled(true);
        teen();
    }//GEN-LAST:event_tblTourMouseClicked
    public void clear(){
        txtMaTour.setText("");
        txtTenTour.setText("");
        txtMaDD.setText("");
        lblHinhTour.setText("");
        txtThoiGian.setText("");
        txtGiaNL.setText("");
        txtMoTa.setText("");
    }
    public void fen(){
        txtMaTour.setEditable(false);
        txtTenTour.setEditable(false);
        txtMaDD.setEditable(false);
        txtThoiGian.setEditable(false);
        txtGiaNL.setEditable(false);
        txtMoTa.setEditable(false);
    }
    public void ten(){
        txtMaTour.setEditable(true);
        txtTenTour.setEditable(true);
        txtMaDD.setEditable(true);
        txtThoiGian.setEditable(true);
        txtGiaNL.setEditable(true);
        txtMoTa.setEditable(true);
    }
    public void teen(){
        txtTenTour.setEditable(true);
        txtMaDD.setEditable(true);
        txtThoiGian.setEditable(true);
        txtGiaNL.setEditable(true);
        txtMoTa.setEditable(true);
    }
    private void btnTaomoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaomoiActionPerformed
        // TODO add your handling code here:
        vh();
        clear();
        btnThem.setEnabled(true);
        lblHinhTour.setEnabled(true);
        ten();
    }//GEN-LAST:event_btnTaomoiActionPerformed
    public boolean checkNullandRegex() {
        if (txtMaTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã tour!");
            txtMaTour.requestFocus();
            return false;
        }
        if (txtMaDD.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã địa điểm!");
            txtMaDD.requestFocus();
            return false;
        }
        if (txtTenTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên tour!");
            txtTenTour.requestFocus();
            return false;
        }
        if (lblHinhTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống hình!");
            return false;
        }
        if (txtThoiGian.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống thời gian!");
            txtThoiGian.requestFocus();
            return false;
        }
        if (txtGiaNL.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống giá!");
            txtGiaNL.requestFocus();
            return false;
        }
        if (txtGiaTE.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống giá!");
            txtGiaTE.requestFocus();
            return false;
        }
        if (txtMoTa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mô tả!");
            txtMoTa.requestFocus();
            return false;
        }
        if(dcNgayBD.getDate().equals("")){
            JOptionPane.showConfirmDialog(this, "Không được để trống ngày bắt đầu!");
            return false;
        }
        if(jDateChooser2.getDate().equals("")){
            JOptionPane.showConfirmDialog(this, "Không được để trống ngày bắt đầu!");
            return false;
        }
        Date BD= dcNgayBD.getDate();
        Date KT= jDateChooser2.getDate();
        if(BD.before(KT)){
            JOptionPane.showMessageDialog(this, "Lỗi: Ngày bắt đầu phải nằm trước ngày kết thúc/Ngày kết thúc phải nằm sau ngày bắt đầu!");
            return false;
        }
        String matourregex="^T\\d{3}$";
        String soregex="^[1-9]\\d*(\\.\\d+)?$";
        if(!txtGiaNL.getText().matches(soregex)){
            JOptionPane.showMessageDialog(this, "Lỗi: Giá trị vừa được nhập vào không phải là số!");
            txtGiaNL.requestFocus();
            return false;
        }
        if(!txtGiaTE.getText().matches(soregex)){
            JOptionPane.showMessageDialog(this, "Lỗi: Giá trị vừa được nhập vào không phải là số!");
            txtGiaTE.requestFocus();
            return false;
        }
        if(!txtMaTour.getText().matches(matourregex)){
            JOptionPane.showMessageDialog(this, "Lỗi: Sai định dạng mã tour, ví dụ đúng: T001");
            txtMaTour.requestFocus();
            return false;
        }
        return true;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(checkNullandRegex()){
        int confirm = JOptionPane.showConfirmDialog(this, "Thêm tour "+txtTenTour.getText()+"", "Xác nhận thêm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
        tour tr = new tour();
        tr.setMaTour(txtMaTour.getText());
        tr.setTenTour(txtTenTour.getText());
        tr.setMaDiaDiem(txtMaDD.getText());
        ImageIcon icon = (ImageIcon) lblHinhTour.getIcon();
        tr.setHinhAnhTour(icon == null ? null : lblHinhTour.getText());
        tr.setThoiGian(txtThoiGian.getText());
        tr.setGiaNguoiLon(Float.parseFloat(txtGiaNL.getText()));
        tr.setGiaTreEm(Float.parseFloat(txtGiaTE.getText()));
        tr.setNgayBatDau(new java.sql.Date(dcNgayBD.getDate().getTime()));
        tr.setNgayKetThuc(new java.sql.Date(jDateChooser2.getDate().getTime()));
        tr.setMoTaTour(txtMoTa.getText());

        try {
            toursc.them(tr);
            lst.add(tr);
            displayToTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        vh();
        fen();
        }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void lblHinhTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhTourMouseClicked
        // TODO add your handling code here:
        String hinh=chinh();
        lblHinhTour.setText(hinh);
        uphinh(hinh);
    }//GEN-LAST:event_lblHinhTourMouseClicked

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        if(txtTimMa.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không để trống ô tìm kiếm!");
        }else if(!txtTimMa.getText().matches("^T\\d{3}$")){
            JOptionPane.showMessageDialog(this, "Lỗi: Sai định dạng mã nhân viên, ví dụ đúng: NV001");
        }else{
        JOptionPane.showMessageDialog(this, "Đã tìm thấy thông tin cho mã tour "+txtTimMa.getText());
        conn=connectdb.getConnection();
        try {
            CallableStatement st=conn.prepareCall("{call sp_timtour(?)}");
            st.setString(1, txtTimMa.getText());
            ResultSet rs=st.executeQuery();
            while(rs.next()){
                txtMaTour.setText(rs.getString("MaTour").trim());
                txtTenTour.setText(rs.getString("TenTour").trim());
                txtMaDD.setText(rs.getString("MaDiaDiem").trim());
                txtThoiGian.setText(rs.getString("ThoiGian").trim());
                txtGiaNL.setText(String.valueOf(rs.getFloat("GiaNguoiLon")));
                txtGiaTE.setText(String.valueOf(rs.getFloat("GiaTreEm")));
                dcNgayBD.setDate(rs.getDate("NgayBatDau"));
                jDateChooser2.setDate(rs.getDate("NgayKetThuc"));
                txtMoTa.setText(rs.getString("MoTaTour").trim());
                uphinh(rs.getString("HinhAnhTour").trim());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả cho "+txtTimMa.getText());
        }
        }
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        lblHinhTour.setEnabled(true);
        teen();
        txtTimMa.setText("");
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
             int confirm = JOptionPane.showConfirmDialog(this, "Xóa tour "+txtTenTour.getText()+" ?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
        int index=tblTour.getSelectedRow();
        try {
            toursc.xoa(txtMaTour.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane.showMessageDialog(this, "Xóa thành công");
        lst.clear();
        try {
            this.getDataTour();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        this.displayToTable();
        vh();
        fen();
        }
         
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(checkNullandRegex()){
            int confirm = JOptionPane.showConfirmDialog(this, "Sửa thông tin tour "+txtTenTour.getText()+" ?", "Xác nhận sửa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
        int index = tblTour.getSelectedRow();
            tour tr = lst.get(index);
            tr.setTenTour(txtTenTour.getText());
            tr.setMaDiaDiem(txtMaDD.getText());
            ImageIcon icon = (ImageIcon) lblHinhTour.getIcon();
            tr.setHinhAnhTour(icon == null ? null : lblHinhTour.getText());
            tr.setThoiGian(txtThoiGian.getText());
            tr.setGiaNguoiLon(Float.parseFloat(txtGiaNL.getText()));
            tr.setGiaTreEm(Float.parseFloat(txtGiaTE.getText()));
            tr.setNgayBatDau(new java.sql.Date(dcNgayBD.getDate().getTime()));
            tr.setNgayKetThuc(new java.sql.Date(jDateChooser2.getDate().getTime()));
            tr.setMoTaTour(txtMoTa.getText());

            try {
                toursc.sua(tr);
                displayToTable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        vh();
        fen();
        }
        }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        this.displayToTable();
        this.displayToControl(index);
        vh();
        fen();
    }//GEN-LAST:event_btnRefreshActionPerformed
    void setColor(JPanel panel){
        panel.setBackground(new Color(29,90,151));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(33,81,129));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tourview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tourview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tourview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tourview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new tourview().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(tourview.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaomoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private com.toedter.calendar.JDateChooser dcNgayBD;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblHinhTour;
    private javax.swing.JTable tblTour;
    private javax.swing.JTextField txtGiaNL;
    private javax.swing.JTextField txtGiaTE;
    private javax.swing.JTextField txtMaDD;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextArea txtTenTour;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtTimMa;
    // End of variables declaration//GEN-END:variables
    void uphinh(String hinh){
        ImageIcon image1=new ImageIcon("src\\img\\"+hinh);
        Image im=image1.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(lblHinhTour.getWidth(), lblHinhTour.getHeight(), im.SCALE_SMOOTH));
        lblHinhTour.setIcon(icon);
    }
    private String chinh(){
        String hinh="";
        JFileChooser open=new JFileChooser();
        File defaultDirectory=new File("src\\img\\"+hinh);
        open.setCurrentDirectory(defaultDirectory);
        int rs=open.showOpenDialog(null);
        if(rs==open.APPROVE_OPTION){
            File f=open.getSelectedFile();
            String filename=f.getAbsolutePath();
            String [] chuoi=filename.split("\\\\");
            hinh=chuoi[chuoi.length-1];
        }
        return hinh;
    }
}

